{
  "recorded_channels":
  [
    {
      "channnel_id":"oss",
      "channel_id":"oss",
      "videos":[
        {
          "id":"sm3527287",
          "title":"Big Buck Bunny",
          "movie_url":"../movie/movie.mp4",
          "thumbnail_url":"ss.png",
          "player_url":"../play.html#0",
          "comment_url":"../comment/0.xml"
        },
        {
          "id":"sm22312215",
          "title":"ビッグバックバニー",
          "movie_url":"../movie/movie.mp4",
          "thumbnail_url":"ss.png",
          "player_url":"../play.html#0",
          "comment_url":"../comment/0.xml"
        }
      ]
    }
   ],
  "recording_channels":[
    {"channel_url":"https://ch.nicovideo.jp/oss","channel_id":"oss"}
  ]
}