{
  "recorded_channels":
  [
    {
      "channnel_id":"channel1",
      "videos":[
        {
          "id":"0",
          "title":"テスト動画",
          "movie_url":"movie.mp4",
          "thumbnail_url":"ss.png",
          "comment_url":"comment.xml"
        }
      ]
    }
   ],
  "recording_channels":[
    {"channel_url":"http://example.com/","channel_id":"channel1"},
  ]
}