{
  "recorded_channels":
  [
    {
      "channnel_id":"channel1",
      "channel_id":"channel1",
      "videos":[
        {
          "id":"0",
          "title":"Big Buck Bunny",
          "movie_url":"movie.mp4",
          "thumbnail_url":"ss.png",
          "player_url":"../play.html#0",
          "comment_url":"comment.xml"
        },
        {
          "id":"0",
          "title":"テスト動画",
          "movie_url":"../movie/movie.mp4",
          "thumbnail_url":"ss.png",
          "player_url":"../play.html#0",
          "comment_url":"../comment/0.xml"
        }
      ]
    }
   ],
  "recording_channels":[
    {"channel_url":"http://example.com/","channel_id":"channel1"}
  ]
}